version: '3.8'

networks:
    net_local:
        external:
            name: net_local

services:
    web:
        image: betox/symfony:5.x-oracle
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
        networks:
            - net_local