version: '3.8'

networks:
    net_service:
        name: net_service

services:
    mailhog:
        image: mailhog/mailhog
        restart: always
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - net_service