version: '3.8'

networks:
    net_mail:
        name: NetMail
        ipam:
            config:
                - subnet: 172.40.0.0/16
services:
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            net_mail:
                ipv4_address: 172.40.40.1