version: '3.8'

networks:
    net_service:
        name: net_service
        driver: bridge

services:
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        restart: always
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
        networks:
            - net_service