version: '3.8'

networks:
    net_mongodb:
        name: NetMongodb
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
volumes:
    dbdata:
        driver: local
        node_modules:

services:
    mongodb:
        image: mongo:4.1.8-xenial
        container_name: mongodb
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - dbdata:/data/mongodb
        networks:
            net_mongodb:
                ipv4_address: 172.40.40.40

