version: '3.8'

networks:
    net_local:
        external:
            name: net_local

services:
    web:
        image: 25watts/wordpress:5.4
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        networks:
            - net_local