version: '3.5'
networks:
    docker-network:
        driver: bridge
volumes:
    # workspace-sync: # se habilita para mac y windows
        # external: true
    dbdata:
        driver: local
services:
    apache:
        image: betox/magento2.x
        build: .
        container_name: my-custom-service-name
        ports:
            - ${APACHE_PORT}:80 # web
            - "9001:9000" # xdebug
            - "443:443"
            # - "35729:35729" # live reload
        volumes:
            #- workspace-sync:/var/www/html:nocopy
            - ${DIR_BASE}:/var/www/html # :consistent, :cached, :delegated
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
            # - ~/.nvm:/var/www/.nvm
        environment:
            XDEBUG_CONFIG: "remote_host=localhost"
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - db
        links:
            - db
        networks:
            - docker-network

    db:
        image: mariadb
        ports:
            - 3300:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - docker-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - UPLOAD_LIMIT=2048M
            - UPLOAD_MAX_FILESIZE=512M
            - MAX_EXECUTION_TIME=38000
        ports:
            - 8080:80
        networks:
            - docker-network

    redis:
        image: redis
        ports:
            - 6379
        networks:
            - docker-network

    redis-session:
        image: redis
        ports:
            - 6379
        networks:
            - docker-network

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - docker-network