version: '3.8'

networks:
    net_database:
        external:
            name: net_database
    net_service:
        external:
            name: net_service

services:
    apache:
        image: betox/php:5.6
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        networks:
            - net_database
            - net_service
