version: '3.8'

networks:
    net_database:
        name: net_database
        driver: bridge

volumes:
    dbdata:
        driver: local

services:
    oracle:
        image: tqldtqmapirails/oracle-xe-12c:latest
        container_name: oracle
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - dbdata:/var/lib/oracle
        networks:
            - net_database