version: '3.8'

networks:
    net_betox:
        name: net_betox

volumes:
    oracle_data:
        driver: local

services:
    oracle:
        image: store/oracle/database-enterprise:12.2.0.1
        container_name: oracle
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - oracle_data:/var/lib/oracle
        networks:
            - net_betox
