version: '3.7'

networks:
    net_oracle:
        name: NetOracle
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
volumes:
    dbdata:
        driver: local

services:
    mysql:
        image: store/oracle/database-enterprise:12.2.0.1
        # restart: always
        container_name: oracle
        ports:
            - 1521:1521
        # environment:
        #     - MYSQL_ROOT_PASSWORD=root
        volumes:
            - dbdata:/var/lib/oracle
        networks:
            net_oracle:
                ipv4_address: 172.20.20.1