version: '3.8'

networks:
    net_oracle:
        name: NetOracle
        driver: bridge
        ipam:
            config:
                - subnet: 172.60.60.0/16
volumes:
    dbdata:
        driver: local

services:
    oracle:
        image: oracleinanutshell/oracle-xe-11g:latest
        container_name: oracle
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - dbdata:/var/lib/oracle
        networks:
            net_oracle:
                ipv4_address: 172.60.60.1