#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===========================================
	v.$version
	Access your new links:
-------------------------------------------
 🌎 -> Web server: http://localhost:85
 ⚙️  -> PHPMyAdmin: http://localhost:8080
 ✉️  -> Local Emails: http://localhost:8025
============================================
"