version: '3.8'

networks:
    net_service:
        external:
            name: net_service
    net_redis:
        external:
            name: NetRedis
    net_mail:
        external:
            name: NetMailHog
services:
    apache:
        image: 25watts/magento2:2.1
        ports:
            - 85:80
            - 443:443
        volumes:
            - apache-sync-jmc:/var/www/html:nocopy,delegated
        networks:
            - net_service
            - net_redis
            - net_mail

volumes:
  apache-sync-jmc:
    external: true