version: '3.8'
networks:
    net_local:
        name: net_local

volumes:
    mongodb_data:
        driver: local

services:
    mongodb:
        image: mongo:4.1.8-xenial
        container_name: mongodb
        restart: unless-stopped
        ports: 
            - 8082:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - mongodb_data:/data/mongodb
        networks:
            - net_local
