version: '3.8'

networks:
    net_db_mongo:
        name: NetDbMongo
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
volumes:
    dbdata:
        driver: local
        node_modules:

services:
    db_mongo:
        image: mongo:4.1.8-xenial
        container_name: db_mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - dbdata:/data/db
        networks:
            net_db_mongo:
                ipv4_address: 172.40.40.40

