version: '3.8'

networks:
    net_local:
        external:
            name: net_local

services:
    web:
        image: betox/php:7.4
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        # environment:
            # XDEBUG_CONFIG: client_host=172.20.0.1 client_port=9002
        networks:
            - net_local