version: '3.8'

networks:
    net_betox:
        name: net_betox

services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
        networks:
            - net_betox