version: '3.8'

networks:
    net_mysql:
        external:
            name: NetMysql
services:
    apache:
        image: betox/php:8.0
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        # environment:
            # PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - net_mysql