version: '3.8'

networks:
    net_database:
        external:
            name: net_database
    net_service:
        external:
            name: net_service

services:
    nodejs:
        image: nodejs
        restart: unless-stopped
        ports:
            - 80:8080
        environment:
            - MONGO_USERNAME=root
            - MONGO_PASSWORD=root
            - MONGO_HOSTNAME=db_mongo
            - MONGO_PORT=8080
            # - MONGO_DB=example
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            net_nodejs:
                ipv4_address: 172.30.30.1
        command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js



