version: '3.8'

networks:
    net_local:
        external:
            name: net_local

volumes:
    mysql_data:
        driver: local
        
services:
    mysql:
        image: mysql
        restart: always
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - net_local

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_mysql
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - UPLOAD_LIMIT=4048M
            - UPLOAD_MAX_FILESIZE=512M
            - MAX_EXECUTION_TIME=38000
        ports:
            - 8080:80
        networks:
            - net_local