version: '3.8'

networks:
    net_service:
        name: net_service

services:
    redis_cache:
        image: redis
        restart: always
        container_name: redis_cache
        ports:
            - 6379
        networks:
            - net_service

    redis_session:
        image: redis
        restart: always
        container_name: redis_session
        ports:
            - 6379
        networks:
            - net_service