version: '3.8'

networks:
    net_mariadb:
        name: NetMariadb
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.20.0/16
volumes:
    dbdata:
        driver: local

services:
    mariadb:
        image: mariadb
        restart: always
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - dbdata:/var/lib/mariadb
        networks:
            net_mariadb:
                ipv4_address: 172.20.20.1
