version: '3.8'

networks:
    net_local:
        external:
            name: net_local

volumes:
    dbdata:
        driver: local

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - dbdata:/var/lib/oracle
        networks:
            - net_local