version: '3.5'

networks:
    net_redis:
        name: NetRedis
        ipam:
            config:
                - subnet: 172.30.0.0/16
services:
    redis-cache:
        image: redis
        # restart: always
        container_name: redis_cache
        ports:
            - 6379
        networks:
            net_redis:
                ipv4_address: 172.30.30.1

    redis-session:
        image: redis
        # restart: always
        container_name: redis_session
        ports:
            - 6379
        networks:
            net_redis:
                ipv4_address: 172.30.30.2