version: '3.8'

networks:
    net_redis:
        name: NetRedis

services:
    redis_cache:
        image: redis
        restart: always
        container_name: redis_cache
        ports:
            - 6379
        networks:
            - net_redis

    redis_session:
        image: redis
        restart: always
        container_name: redis_session
        ports:
            - 6379
        networks:
            - net_redis